[program:laravel-reverb]
process_name=%(program_name)s
command=php /var/www/restaurante/artisan reverb:start --host=0.0.0.0 --port=8080
directory=/var/www/restaurante
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/restaurante/storage/logs/reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600

; Variáveis de ambiente (copia do .env)
environment=
    BROADCAST_CONNECTION="reverb",
    REVERB_APP_ID="yumgo",
    REVERB_APP_KEY="t9pg2dslmpl5y1cp6rrf",
    REVERB_APP_SECRET="nnrgrbvbyzaolvzflqpo",
    REVERB_HOST="0.0.0.0",
    REVERB_PORT="8080",
    REVERB_SCHEME="http"
