[program:laravel-queue-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/restaurante/artisan queue:work redis --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=4
redirect_stderr=true
stdout_logfile=/var/www/restaurante/storage/logs/queue-default.log
stopwaitsecs=3600
