[program:laravel-queue-nfce]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/restaurante/artisan queue:work redis --queue=nfce --sleep=3 --tries=3 --max-time=3600 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/restaurante/storage/logs/queue-nfce.log
stopwaitsecs=3600
